# Generated by Django 2.2 on 2021-05-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20210509_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dojo',
            new_name='dojos',
        ),
    ]
